# -*- coding: utf-8 -*-
"""
@File    :   github_utils.py
@Author  :   qfding
@Date    :   2026-06-02
@Desc    :   This file contains the definition of the github_utils.
"""
from constants import agent_constants, section_constants


def get_previous_plan(issue):
    """Scans the issue comments to find the most recent plan generated by the bot."""
    print("Retrieving previous plan...")
    comments = list(issue.get_comments())
    for comment in reversed(comments):
        if (agent_constants.PLANNER_SIGNATURE in comment.body and
                section_constants.PLAN_DRAFT in comment.body):
            return comment.body
    return ""


def get_approved_plan(issue):
    """Scans the issue to find the final approved plan from the Planner Agent."""
    print("Retrieving approved plan...")
    comments = list(issue.get_comments())
    for comment in reversed(comments):
        if (agent_constants.PLANNER_SIGNATURE in comment.body and
                section_constants.PLAN_DRAFT in comment.body):
            return comment.body
    return ""


def get_evaluator_reject_number(issue):
    """Scans the issue to find the final approved plan from the Planner Agent."""
    print("Retrieving evaluator reject number...")
    reject_numbers = 0
    comments = list(issue.get_comments())
    for comment in reversed(comments):
        if (agent_constants.EVALUATOR_SIGNATURE in comment.body and
                section_constants.EVALUATOR_EXEC_COMPLETE in comment.body and
                section_constants.TEST_REJECTED in comment.body
        ):
            reject_numbers += 1
    return reject_numbers


def get_evaluator_reject_content(issue):
    """Scans the issue to find the final approved plan from the Planner Agent."""
    print("Retrieving evaluator reject content...")
    comments = list(issue.get_comments())
    for comment in reversed(comments):
        if (agent_constants.EVALUATOR_SIGNATURE in comment.body and
                section_constants.EVALUATOR_EXEC_COMPLETE in comment.body and
                section_constants.TEST_REJECTED in comment.body
        ):
            return comment.body
    return ""


def get_latest_generator_summary(issue):
    """Scans the issue to find the latest generator from the Generator Agent."""
    print("Retrieving latest generator summary...")
    comments = list(issue.get_comments())
    for comment in reversed(comments):
        if (agent_constants.GENERATOR_SIGNATURE in comment.body and
                section_constants.GENERATOR_EXEC_COMPLETE in comment.body):
            return comment.body
    return ""
