# -*- coding: utf-8 -*-
"""
@File    :   github_utils.py
@Author  :   qfding
@Date    :   2026-06-02
@Desc    :   This file contains the definition of the github_utils.
"""
from constants import agent_constants, label_constants, section_constants


def switch_status_label(issue, new_label):
    """Enforces a single pipeline state on the issue: removes every existing
    status:* label, then applies new_label. Non-status labels (bug, enhancement,
    user-applied labels, ...) are preserved. Use this for every pipeline state
    transition so stale trigger labels never pile up."""
    for label in issue.labels:
        if label.name.startswith(label_constants.STATUS_PREFIX) and label.name != new_label:
            issue.remove_from_labels(label.name)
    issue.add_to_labels(new_label)


def get_previous_plan(issue):
    """Scans the issue comments to find the most recent plan generated by the bot."""
    print("Retrieving previous plan...")
    comments = list(issue.get_comments())
    for comment in reversed(comments):
        if (agent_constants.PLANNER_SIGNATURE in comment.body and
                section_constants.PLAN_DRAFT in comment.body):
            return comment.body
    return ""


def get_approved_plan(issue):
    """Scans the issue to find the final approved plan from the Planner Agent."""
    print("Retrieving approved plan...")
    comments = list(issue.get_comments())
    for comment in reversed(comments):
        if (agent_constants.PLANNER_SIGNATURE in comment.body and
                section_constants.PLAN_DRAFT in comment.body):
            return comment.body
    return ""


def get_evaluator_reject_number(issue):
    """Scans the issue to find total evaluator reject number"""
    print("Retrieving evaluator reject number...")
    reject_numbers = 0
    comments = list(issue.get_comments())
    for comment in reversed(comments):
        if (agent_constants.EVALUATOR_SIGNATURE in comment.body and
                section_constants.EVALUATOR_EXEC_COMPLETE in comment.body and
                section_constants.TEST_REJECTED in comment.body
        ):
            reject_numbers += 1
    return reject_numbers


def get_evaluator_reject_number_after_approved(issue):
    """Scans the issue to find evaluator reject number after approved."""
    print("Retrieving evaluator reject number after approved...")
    reject_numbers = 0
    comments = list(issue.get_comments())
    for comment in reversed(comments):
        if (agent_constants.PLANNER_SIGNATURE in comment.body and
                section_constants.PLAN_APPROVED in comment.body):
            return reject_numbers
        if (agent_constants.EVALUATOR_SIGNATURE in comment.body and
                section_constants.EVALUATOR_EXEC_COMPLETE in comment.body and
                section_constants.TEST_REJECTED in comment.body
        ):
            reject_numbers += 1
    return reject_numbers


def get_evaluator_reject_content(issue):
    """Scans the issue to find the final approved plan from the Planner Agent."""
    print("Retrieving evaluator reject content...")
    comments = list(issue.get_comments())
    for comment in reversed(comments):
        if (agent_constants.EVALUATOR_SIGNATURE in comment.body and
                section_constants.EVALUATOR_EXEC_COMPLETE in comment.body and
                section_constants.TEST_REJECTED in comment.body
        ):
            return comment.body
    return ""


def get_latest_generator_summary(issue):
    """Scans the issue to find the latest generator from the Generator Agent."""
    print("Retrieving latest generator summary...")
    comments = list(issue.get_comments())
    for comment in reversed(comments):
        if (agent_constants.GENERATOR_SIGNATURE in comment.body and
                section_constants.GENERATOR_EXEC_COMPLETE in comment.body):
            return comment.body
    return ""


def get_latest_test_generator_summary(issue):
    """Scans the issue to find the latest generator from the Generator Agent."""
    print("Retrieving latest test generator summary...")
    comments = list(issue.get_comments())
    for comment in reversed(comments):
        if (agent_constants.TEST_GENERATOR_SIGNATURE in comment.body and
                section_constants.TEST_GENERATOR_EXEC_COMPLETE in comment.body):
            return comment.body
    return ""


def get_latest_test_runner_result(issue):
    """Scans the issue to find the latest test execution result from the Test Runner Agent."""
    print("Retrieving latest test runner result...")
    comments = list(issue.get_comments())
    for comment in reversed(comments):
        if (agent_constants.TEST_RUNNER_SIGNATURE in comment.body and
                (section_constants.TEST_RUNNER_EXEC_COMPLETE in comment.body or
                 section_constants.TEST_RUNNER_EXEC_ERROR in comment.body)):
            return comment.body
    return ""
